### ISSUE TITLE
Problem when render "share example" in iOS

### ISSUE THREAD

**Issue by KimleangSama** [shirvanie/flutter_sliding_box#4]
<img width="415" alt="SCR-20240601-trgl" src="https://github.com/shirvanie/flutter_sliding_box/assets/56532167/6ab71c52-50d2-41cf-8aa6-e8674ec90312">

**Comment by shirvanie** [comment]
This is because SlidingBox uses `SafeArea`

To solve this problem, you can move the box

 One way is to use transform:

` return Transform(
    transform: Matrix4.translationValues(0, 15, 0),
    child: SlidingBox(),
  )`
